### ISSUE TITLE
Story

### ISSUE THREAD

**Issue by SaskiaBLittle** [smitja21/vq-the-game-2#1]
Check story grammar and how the story is written / plays out.
Make sure that all of the story flows with each other so that it makes sense to the player.
Also make the room names memorable and get told which rooms you have been in so you don't get confused with where you have been.

Could possibly make a system for when you re enter the hallway after entering a room it sets a bool to true and unlocks a new story text part so that the user gets more input / it could say "you have enter these rooms..."

**Comment by SaskiaBLittle** [comment]
Could possibly make a system for when you re enter the hallway after entering a room it sets a bool to true and unlocks a new story text part so that the user gets more input / it could say "you have enter these rooms..."

**Comment by SaskiaBLittle** [comment]
Split into parts, such as working on one floor at a time

**Comment by ZandarB** [comment]
Story is very story'y. 10/10 would read later
