### ISSUE TITLE
User input error checking 

### ISSUE THREAD

**Issue by marojm1** [smitja21/vq-the-game-2#2]
Game breaks when user enters wrong input and improve ending

**Comment by marojm1** [comment]
Resources needed to load the image: 

- https://www.leadtools.com/help/sdk/tutorials/dotnet-console-load-and-save-images.html
- https://www.codeproject.com/articles/3703/how-to-load-display-images-with-c
- https://www.codeproject.com/questions/838340/display-image-using-windows-console-application-in

**Comment by smitja21** [comment]
I've implemented a lot of error checking, I haven't touched the ending though
