### ISSUE TITLE
Improving Navigation

### ISSUE THREAD

**Issue by smitja21** [smitja21/vq-the-game-2#3]
Making navigation more user friendly, by changing what the user is required to enter to navigate to a new room.

Making navigation options more clear too. Currently can be hard for the user to know what to press/type.

**Comment by ZandarB** [comment]
improve code issues with navigation, namely going into rooms multiple times, being brought to one room multiple times

**Comment by smitja21** [comment]
Make sure the user has a great idea of where the user is at

**Comment by smitja21** [comment]
Resolved
