### ISSUE TITLE
General Bugfixes

### ISSUE THREAD

**Issue by ZandarB** [smitja21/vq-the-game-2#39]
Title, more or less the same. combing the game for any errors

**Comment by ZandarB** [comment]
Fixed Farmbot fight kicking you out to the hallway before moving to the win method

**Comment by ZandarB** [comment]
fixed being able to go into D312 infinitly

**Comment by ZandarB** [comment]
fixed general user input errors using do while loops

**Comment by ZandarB** [comment]
fixed common room being hidden by default despite being needed to progress

**Comment by SaskiaBLittle** [comment]
This has now been merged
