### ISSUE TITLE
Improve Combat

### ISSUE THREAD

**Issue by ZandarB** [smitja21/vq-the-game-2#6]
Add more feedback to the user explaining what is happening, improve the way the dialogue for the combat is presented to the user, maybe for the first fight give the user a mini tutorial on how the combat works, as well as present the % values for hit/miss, so the user can understand the risk/reward between strong and weak attacks

**Comment by ZandarB** [comment]
Also improve the combats code, the chance to hit, the damage multipliers and the damage itself*

**Comment by ZandarB** [comment]
Newly Implimented tips menu isnt an option in the fight menu

**Comment by smitja21** [comment]
This has been resolved
