### ISSUE TITLE
Adding more working items

### ISSUE THREAD

**Issue by SaskiaBLittle** [smitja21/vq-the-game-2#7]
There are more items within the game that the user can interact with.
Similar to the pen we could have other items that you could choose to pick up that cause you to fight less or vise versa picking up the wrong item could cause a fight to occur. (This can be explained to the user at the beginning so that they know the risk)
There could also be specific items that you need to advance in the story (e.g. a Key to open a door). You could receive these from fights or just find them if you explore the room.

**Comment by smitja21** [comment]
I included a "Key" item in level 3 which you must get from Paul to be able to enter Vaughn's office

**Comment by ZandarB** [comment]
i added a new item that leads to a secret boss, the bitcoin wallet. this powers up the buisness student fight

**Comment by ZandarB** [comment]
Finished adding new items
